### ISSUE TITLE
chore: Delete files in EN css folder

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#133]
css/beta/ilp.css
css/do-dont-draft-layout-tweaks.css
css/jquery.dataTables.css
css/mr-bullets.css
css/responsive-tables.css
css/social-media.css

these files have been marked for deletion. Please note another file in this folder is marked to be moved in GC-proto

**Comment by jmealing** [comment]
I actually think I need all these files, I didn't notice this ticket. Can we please recover them to experimental?

**Comment by delisma** [comment]
When I scanned the repo for their use, these files weren't used anywhere.

**Comment by jmealing** [comment]
`css/responsive-tables.css` and `css/jquery.dataTables.css` and `css/do-dont-draft-layout-tweaks.css`
 are part of the DS work Miguel was working on with those new layout/demo pages. Maybe it showed no files were using them because these files they were linked to were moved first.

The rest was mine for the ILP page, but I see they're actually already moved into experimental
